apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tooling-app
  name: tooling-app
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: tooling-app
  type: NodePort
status:
  loadBalancer: {}
